---
title: "Comparison of predictions"
author: "Karla Monterrubio-Gómez, Nathan Constantine-Cooke, and Catalina Vallejos"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    toc: yes
    css: style.css
    theme: simplex
    highlight: textmate
    includes:
      in_header: head.html
      before_body: navbar.html
    self_contained: false
    toc_float:
      collapsed: no
link-citations: yes
bibliography: references.bib
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache = TRUE
)
```


# Loading predictions

Here, we load the predicted probabilities of observing an event of type 1 by
$t=5$ that were obtained by different methods


```{r load_pred}
pred_CIF <- read.csv("../Predictions/pred_CIF.csv")
pred_Others <- read.csv("../Predictions/pred_Others.csv")
pred_All <- merge(pred_CIF, pred_Others, by = "testID")
```

```{r cor_pred}
library(corrplot)
pred_cor <- cor(pred_All[,-1])
corrplot(pred_cor)

plot(pred_All[,-1])
```


# References
<div id="refs"></div>

# Session Info
```{r}
sessionInfo()
```
